(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
!function(){if("Promise"in window){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),s=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),i=location.href.replace(/#[^#]+$/,"");o.add(i);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(s){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var i=new XMLHttpRequest;i.open("GET",t,i.withCredentials=!0),i.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},l={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},l),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},l)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var e=document.querySelector('.js344');e.setAttribute('src',(dpi>1)?'images/logo-404.png':'images/logo-202.png');
var e=document.querySelector('.js345');e.setAttribute('src',(dpi>1)?'images/home-admin-60.png':'images/home-admin-30.png');
var e=document.querySelector('.js346');e.setAttribute('src',(dpi>1)?'images/post-60.png':'images/post-30.png');
var e=document.querySelector('.js347');e.setAttribute('src',(dpi>1)?'images/pages-60.png':'images/pages-30.png');
var e=document.querySelector('.js348');e.setAttribute('src',(dpi>1)?'images/media-60.png':'images/media-30.png');
var e=document.querySelector('.js349');e.setAttribute('src',(dpi>1)?'images/edit-pst-60.png':'images/edit-pst-30.png');
var e=document.querySelector('.js350');e.setAttribute('src',(dpi>1)?'images/delete-60.png':'images/delete-30.png');
var e=document.querySelector('.js351');e.setAttribute('src',(dpi>1)?'images/settings-60.png':'images/settings-30.png');
var e=document.querySelector('.js352');e.setAttribute('src','images/search-40.png');
var e=document.querySelector('.js353');e.setAttribute('src','images/close-icon-40.png');
var e=document.querySelector('.js355');e.setAttribute('src','images/public-36.png');
var e=document.querySelector('.js356');e.setAttribute('src',(dpi>1)?'images/calender-admin-60.png':'images/calender-admin-30.png');
var e=document.querySelector('.js357');e.setAttribute('src',(dpi>1)?'images/clock-60.png':'images/clock-30.png');
var e=document.querySelector('.js358');e.setAttribute('src',(dpi>1)?'images/add-post-46.png':'images/add-post-23.png');}else if($(window).width()>=960){var e=document.querySelector('.js344');e.setAttribute('src',(dpi>1)?'images/logo-274.png':'images/logo-137.png');
var e=document.querySelector('.js345');e.setAttribute('src',(dpi>1)?'images/home-admin-48.png':'images/home-admin-24-2.png');
var e=document.querySelector('.js346');e.setAttribute('src',(dpi>1)?'images/post-48.png':'images/post-24.png');
var e=document.querySelector('.js347');e.setAttribute('src',(dpi>1)?'images/pages-48.png':'images/pages-24-2.png');
var e=document.querySelector('.js348');e.setAttribute('src',(dpi>1)?'images/media-48.png':'images/media-24-2.png');
var e=document.querySelector('.js349');e.setAttribute('src',(dpi>1)?'images/edit-pst-48.png':'images/edit-pst-24-2.png');
var e=document.querySelector('.js350');e.setAttribute('src',(dpi>1)?'images/delete-48.png':'images/delete-24-2.png');
var e=document.querySelector('.js351');e.setAttribute('src',(dpi>1)?'images/settings-48.png':'images/settings-24-2.png');
var e=document.querySelector('.js352');e.setAttribute('src','images/search-32-1.png');
var e=document.querySelector('.js353');e.setAttribute('src','images/close-icon-32.png');
var e=document.querySelector('.js355');e.setAttribute('src',(dpi>1)?'images/public-56.png':'images/public-28-1.png');
var e=document.querySelector('.js356');e.setAttribute('src',(dpi>1)?'images/calender-admin-48.png':'images/calender-admin-24-2.png');
var e=document.querySelector('.js357');e.setAttribute('src',(dpi>1)?'images/clock-48.png':'images/clock-24-2.png');
var e=document.querySelector('.js358');e.setAttribute('src',(dpi>1)?'images/add-post-38.png':'images/add-post-19.png');}else if($(window).width()>=768){var e=document.querySelector('.js344');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-330.png':'images/logo-220.png'):'images/logo-110.png');
var e=document.querySelector('.js345');e.setAttribute('src',(dpi>1)?'images/home-admin-38.png':'images/home-admin-19.png');
var e=document.querySelector('.js346');e.setAttribute('src',(dpi>1)?'images/post-38.png':'images/post-19.png');
var e=document.querySelector('.js347');e.setAttribute('src',(dpi>1)?'images/pages-38.png':'images/pages-19.png');
var e=document.querySelector('.js348');e.setAttribute('src',(dpi>1)?'images/media-38.png':'images/media-19.png');
var e=document.querySelector('.js349');e.setAttribute('src',(dpi>1)?'images/edit-pst-38.png':'images/edit-pst-19.png');
var e=document.querySelector('.js350');e.setAttribute('src',(dpi>1)?'images/delete-38.png':'images/delete-19.png');
var e=document.querySelector('.js351');e.setAttribute('src',(dpi>1)?'images/settings-38.png':'images/settings-19.png');
var e=document.querySelector('.js352');e.setAttribute('src',(dpi>1)?'images/search-50.png':'images/search-25.png');
var e=document.querySelector('.js353');e.setAttribute('src',(dpi>1)?'images/close-icon-50.png':'images/close-icon-25.png');
var e=document.querySelector('.js355');e.setAttribute('src',(dpi>1)?'images/public-44.png':'images/public-22.png');
var e=document.querySelector('.js356');e.setAttribute('src',(dpi>1)?'images/calender-admin-38.png':'images/calender-admin-19.png');
var e=document.querySelector('.js357');e.setAttribute('src',(dpi>1)?'images/clock-38.png':'images/clock-19.png');
var e=document.querySelector('.js358');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/add-post-45.png':'images/add-post-30.png'):'images/add-post-15.png');}else if($(window).width()>=480){var e=document.querySelector('.js344');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-207.png':'images/logo-138-1.png'):'images/logo-69.png');
var e=document.querySelector('.js345');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/home-admin-36.png':'images/home-admin-24-1.png'):'images/home-admin-12.png');
var e=document.querySelector('.js346');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/post-33.png':'images/post-22.png'):'images/post-11.png');
var e=document.querySelector('.js347');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/pages-36.png':'images/pages-24-1.png'):'images/pages-12.png');
var e=document.querySelector('.js348');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/media-36.png':'images/media-24-1.png'):'images/media-12.png');
var e=document.querySelector('.js349');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/edit-pst-36.png':'images/edit-pst-24-1.png'):'images/edit-pst-12.png');
var e=document.querySelector('.js350');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/delete-36.png':'images/delete-24-1.png'):'images/delete-12.png');
var e=document.querySelector('.js351');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/settings-36.png':'images/settings-24-1.png'):'images/settings-12.png');
var e=document.querySelector('.js352');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/search-45.png':'images/search-30-1.png'):'images/search-15.png');
var e=document.querySelector('.js353');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/close-icon-45.png':'images/close-icon-30-1.png'):'images/close-icon-15.png');
var e=document.querySelector('.js355');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/public-42.png':'images/public-28.png'):'images/public-14.png');
var e=document.querySelector('.js356');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calender-admin-36.png':'images/calender-admin-24-1.png'):'images/calender-admin-12.png');
var e=document.querySelector('.js357');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/clock-36.png':'images/clock-24-1.png'):'images/clock-12.png');
var e=document.querySelector('.js358');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/add-post-27.png':'images/add-post-18-1.png'):'images/add-post-9.png');}else{var e=document.querySelector('.js344');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-138.png':'images/logo-92.png'):'images/logo-46.png');
var e=document.querySelector('.js345');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/home-admin-24.png':'images/home-admin-16.png'):'images/home-admin-8.png');
var e=document.querySelector('.js346');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/post-21.png':'images/post-14.png'):'images/post-7.png');
var e=document.querySelector('.js347');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/pages-24.png':'images/pages-16.png'):'images/pages-8.png');
var e=document.querySelector('.js348');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/media-24.png':'images/media-16.png'):'images/media-8.png');
var e=document.querySelector('.js349');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/edit-pst-24.png':'images/edit-pst-16.png'):'images/edit-pst-8.png');
var e=document.querySelector('.js350');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/delete-24.png':'images/delete-16.png'):'images/delete-8.png');
var e=document.querySelector('.js351');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/settings-24.png':'images/settings-16.png'):'images/settings-8.png');
var e=document.querySelector('.js352');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/search-30.png':'images/search-20.png'):'images/search-10.png');
var e=document.querySelector('.js353');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/close-icon-30.png':'images/close-icon-20.png'):'images/close-icon-10.png');
var e=document.querySelector('.js355');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/public-27.png':'images/public-18.png'):'images/public-9.png');
var e=document.querySelector('.js356');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calender-admin-24.png':'images/calender-admin-16.png'):'images/calender-admin-8.png');
var e=document.querySelector('.js357');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/clock-24.png':'images/clock-16.png'):'images/clock-8.png');
var e=document.querySelector('.js358');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/add-post-18.png':'images/add-post-12.png'):'images/add-post-6.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
$('form').h5Validate();
});