(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),s=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),i=location.href.replace(/#[^#]+$/,"");o.add(i);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(s){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var i=new XMLHttpRequest;i.open("GET",t,i.withCredentials=!0),i.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},l={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},l),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},l)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/logo-404.png':'images/logo-202.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-393.png':'images/playstore-262.png'):'images/playstore-131.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-93.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-62.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-31.png');
var e=document.querySelector('.js4');e.setAttribute('src','images/search-40.png');
var a='data-src';var e=document.querySelector('.js5 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/2021-07-1200.png');
var a='data-src';var e=document.querySelector('.js5 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/deploy-1200.png');
var a='data-src';var e=document.querySelector('.js5 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/after-1200.png');
var e=document.querySelector('.js6');e.setAttribute('src','images/governor-1200.png');
var e=document.querySelector('.js7');e.setAttribute('src','images/work-150.png');
var e=document.querySelector('.js8');e.setAttribute('src','images/we-re-proud-150.png');
var e=document.querySelector('.js9');e.setAttribute('src','images/health-150.png');
var e=document.querySelector('.js10');e.setAttribute('src','images/abuja-bank-1200.jpg');
var e=document.querySelector('.js11');e.setAttribute('src','images/4769-150.png');
var e=document.querySelector('.js12');e.setAttribute('src','images/nnpc-150.png');
var e=document.querySelector('.js13');e.setAttribute('src','images/mtn-150.png');
var e=document.querySelector('.js14');e.setAttribute('src','images/oghene-1200.png');
var e=document.querySelector('.js15');e.setAttribute('src','images/re-innovation-150.png');
var e=document.querySelector('.js16');e.setAttribute('src','images/delta-150.png');
var e=document.querySelector('.js17');e.setAttribute('src','images/engr-ma-150.png');
var e=document.querySelector('.js18');e.setAttribute('src','images/medal-1200.png');
var e=document.querySelector('.js19');e.setAttribute('src','images/south-150.png');
var e=document.querySelector('.js20');e.setAttribute('src','images/southee-150.png');
var e=document.querySelector('.js21');e.setAttribute('src','images/success-150.png');
var e=document.querySelector('.js22');e.setAttribute('src','images/amandabig-1200.jpg');
var e=document.querySelector('.js23');e.setAttribute('src','images/amanda-small-150.png');
var e=document.querySelector('.js24');e.setAttribute('src','images/irrfan-150.png');
var e=document.querySelector('.js25');e.setAttribute('src','images/apee-150.png');
var a='data-src';var e=document.querySelector('.js26');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer1-110-1.png');
var a='data-src';var e=document.querySelector('.js27');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer4-110-1.png');
var a='data-src';var e=document.querySelector('.js28');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer2-110-1.png');
var a='data-src';var e=document.querySelector('.js29');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer5-110-1.png');
var a='data-src';var e=document.querySelector('.js30');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer3-110-1.png');
var a='data-src';var e=document.querySelector('.js31');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer6-110-1.png');
var a='data-src';var e=document.querySelector('.js32');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-120.png':'images/facebook-80.png'):'images/facebook-40.png');
var a='data-src';var e=document.querySelector('.js33');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-120.png':'images/twitter-80.png'):'images/twitter-40.png');
var a='data-src';var e=document.querySelector('.js34');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-120.png':'images/instagram-80.png'):'images/instagram-40.png');
var a='data-src';var e=document.querySelector('.js35');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-120.png':'images/youtube-80.png'):'images/youtube-40.png');}else if($(window).width()>=960){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?'images/logo-274.png':'images/logo-137.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-312.png':'images/playstore-208.png'):'images/playstore-104.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-75.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-50.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-25.png');
var e=document.querySelector('.js4');e.setAttribute('src','images/search-32-1.png');
var a='data-src';var e=document.querySelector('.js5 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/2021-07-960-2.png');
var a='data-src';var e=document.querySelector('.js5 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/deploy-960-2.png');
var a='data-src';var e=document.querySelector('.js5 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/after-960-2.png');
var e=document.querySelector('.js6');e.setAttribute('src','images/governor-960-2.png');
var e=document.querySelector('.js7');e.setAttribute('src','images/work-120.png');
var e=document.querySelector('.js8');e.setAttribute('src','images/we-re-proud-120.png');
var e=document.querySelector('.js9');e.setAttribute('src','images/health-120.png');
var e=document.querySelector('.js10');e.setAttribute('src','images/abuja-bank-960-2.jpg');
var e=document.querySelector('.js11');e.setAttribute('src','images/4769-120.png');
var e=document.querySelector('.js12');e.setAttribute('src','images/nnpc-120.png');
var e=document.querySelector('.js13');e.setAttribute('src','images/mtn-120.png');
var e=document.querySelector('.js14');e.setAttribute('src','images/oghene-960-2.png');
var e=document.querySelector('.js15');e.setAttribute('src','images/re-innovation-120.png');
var e=document.querySelector('.js16');e.setAttribute('src','images/delta-120.png');
var e=document.querySelector('.js17');e.setAttribute('src','images/engr-ma-120.png');
var e=document.querySelector('.js18');e.setAttribute('src','images/medal-960-2.png');
var e=document.querySelector('.js19');e.setAttribute('src','images/south-120.png');
var e=document.querySelector('.js20');e.setAttribute('src','images/southee-120.png');
var e=document.querySelector('.js21');e.setAttribute('src','images/success-120.png');
var e=document.querySelector('.js22');e.setAttribute('src','images/amandabig-960-2.jpg');
var e=document.querySelector('.js23');e.setAttribute('src','images/amanda-small-120.png');
var e=document.querySelector('.js24');e.setAttribute('src','images/irrfan-120.png');
var e=document.querySelector('.js25');e.setAttribute('src','images/apee-120.png');
var a='data-src';var e=document.querySelector('.js26');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer1-88-1.png');
var a='data-src';var e=document.querySelector('.js27');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer4-88.png');
var a='data-src';var e=document.querySelector('.js28');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer2-88-1.png');
var a='data-src';var e=document.querySelector('.js29');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer5-88-1.png');
var a='data-src';var e=document.querySelector('.js30');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer3-88.png');
var a='data-src';var e=document.querySelector('.js31');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer6-88.png');
var a='data-src';var e=document.querySelector('.js32');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-96.png':'images/facebook-64.png'):'images/facebook-32-1.png');
var a='data-src';var e=document.querySelector('.js33');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-96.png':'images/twitter-64.png'):'images/twitter-32-1.png');
var a='data-src';var e=document.querySelector('.js34');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-96.png':'images/instagram-64.png'):'images/instagram-32-1.png');
var a='data-src';var e=document.querySelector('.js35');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-96.png':'images/youtube-64.png'):'images/youtube-32-1.png');}else if($(window).width()>=768){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-330.png':'images/logo-220.png'):'images/logo-110.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-252.png':'images/playstore-168.png'):'images/playstore-84.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-60.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-40.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-20.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?'images/search-52.png':'images/search-26.png');
var a='data-src';var e=document.querySelector('.js5 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/2021-07-1536.png':'images/2021-07-768.png');
var a='data-src';var e=document.querySelector('.js5 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/deploy-1536.png':'images/deploy-768.png');
var a='data-src';var e=document.querySelector('.js5 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/after-1536.png':'images/after-768.png');
var e=document.querySelector('.js6');e.setAttribute('src',(dpi>1)?'images/governor-1536.png':'images/governor-768.png');
var e=document.querySelector('.js7');e.setAttribute('src',(dpi>1)?'images/work-192.png':'images/work-96.png');
var e=document.querySelector('.js8');e.setAttribute('src',(dpi>1)?'images/we-re-proud-192.png':'images/we-re-proud-96.png');
var e=document.querySelector('.js9');e.setAttribute('src',(dpi>1)?'images/health-192.png':'images/health-96.png');
var e=document.querySelector('.js10');e.setAttribute('src',(dpi>1)?'images/abuja-bank-1536.jpg':'images/abuja-bank-768.jpg');
var e=document.querySelector('.js11');e.setAttribute('src',(dpi>1)?'images/4769-192.png':'images/4769-96.png');
var e=document.querySelector('.js12');e.setAttribute('src',(dpi>1)?'images/nnpc-192.png':'images/nnpc-96.png');
var e=document.querySelector('.js13');e.setAttribute('src',(dpi>1)?'images/mtn-192.png':'images/mtn-96.png');
var e=document.querySelector('.js14');e.setAttribute('src',(dpi>1)?'images/oghene-1536.png':'images/oghene-768.png');
var e=document.querySelector('.js15');e.setAttribute('src',(dpi>1)?'images/re-innovation-192.png':'images/re-innovation-96.png');
var e=document.querySelector('.js16');e.setAttribute('src',(dpi>1)?'images/delta-192.png':'images/delta-96.png');
var e=document.querySelector('.js17');e.setAttribute('src',(dpi>1)?'images/engr-ma-192.png':'images/engr-ma-96.png');
var e=document.querySelector('.js18');e.setAttribute('src',(dpi>1)?'images/medal-1536.png':'images/medal-768.png');
var e=document.querySelector('.js19');e.setAttribute('src',(dpi>1)?'images/south-192.png':'images/south-96.png');
var e=document.querySelector('.js20');e.setAttribute('src',(dpi>1)?'images/southee-192.png':'images/southee-96.png');
var e=document.querySelector('.js21');e.setAttribute('src',(dpi>1)?'images/success-192.png':'images/success-96.png');
var e=document.querySelector('.js22');e.setAttribute('src',(dpi>1)?'images/amandabig-1536.jpg':'images/amandabig-768.jpg');
var e=document.querySelector('.js23');e.setAttribute('src',(dpi>1)?'images/amanda-small-192.png':'images/amanda-small-96.png');
var e=document.querySelector('.js24');e.setAttribute('src',(dpi>1)?'images/irrfan-192.png':'images/irrfan-96.png');
var e=document.querySelector('.js25');e.setAttribute('src',(dpi>1)?'images/apee-192.png':'images/apee-96.png');
var a='data-src';var e=document.querySelector('.js26');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer1-140.png':'images/footer1-70.png');
var a='data-src';var e=document.querySelector('.js27');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer4-140.png':'images/footer4-70.png');
var a='data-src';var e=document.querySelector('.js28');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer2-140.png':'images/footer2-70.png');
var a='data-src';var e=document.querySelector('.js29');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer5-140.png':'images/footer5-70.png');
var a='data-src';var e=document.querySelector('.js30');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer3-140.png':'images/footer3-70.png');
var a='data-src';var e=document.querySelector('.js31');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer6-140.png':'images/footer6-70.png');
var a='data-src';var e=document.querySelector('.js32');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-75.png':'images/facebook-50.png'):'images/facebook-25.png');
var a='data-src';var e=document.querySelector('.js33');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-75.png':'images/twitter-50.png'):'images/twitter-25.png');
var a='data-src';var e=document.querySelector('.js34');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-78.png':'images/instagram-52.png'):'images/instagram-26.png');
var a='data-src';var e=document.querySelector('.js35');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-78.png':'images/youtube-52.png'):'images/youtube-26.png');}else if($(window).width()>=480){var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-207.png':'images/logo-138-1.png'):'images/logo-69.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-150.png':'images/playstore-100.png'):'images/playstore-50.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-39.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-26.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-13.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/search-48.png':'images/search-32.png'):'images/search-16.png');
var a='data-src';var e=document.querySelector('.js5 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/2021-07-1440.png':'images/2021-07-960-1.png'):'images/2021-07-480.png');
var a='data-src';var e=document.querySelector('.js5 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/deploy-1440.png':'images/deploy-960-1.png'):'images/deploy-480.png');
var a='data-src';var e=document.querySelector('.js5 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/after-1440.png':'images/after-960-1.png'):'images/after-480.png');
var e=document.querySelector('.js6');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/governor-1440.png':'images/governor-960-1.png'):'images/governor-480.png');
var e=document.querySelector('.js7');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/work-177.png':'images/work-118.png'):'images/work-59.png');
var e=document.querySelector('.js8');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/we-re-proud-177.png':'images/we-re-proud-118.png'):'images/we-re-proud-59.png');
var e=document.querySelector('.js9');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/health-177.png':'images/health-118.png'):'images/health-59.png');
var e=document.querySelector('.js10');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/abuja-bank-1440.jpg':'images/abuja-bank-960-1.jpg'):'images/abuja-bank-480.jpg');
var e=document.querySelector('.js11');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/4769-177.png':'images/4769-118.png'):'images/4769-59.png');
var e=document.querySelector('.js12');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/nnpc-177.png':'images/nnpc-118.png'):'images/nnpc-59.png');
var e=document.querySelector('.js13');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/mtn-177.png':'images/mtn-118.png'):'images/mtn-59.png');
var e=document.querySelector('.js14');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/oghene-1440.png':'images/oghene-960-1.png'):'images/oghene-480.png');
var e=document.querySelector('.js15');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/re-innovation-177.png':'images/re-innovation-118.png'):'images/re-innovation-59.png');
var e=document.querySelector('.js16');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/delta-177.png':'images/delta-118.png'):'images/delta-59.png');
var e=document.querySelector('.js17');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/engr-ma-177.png':'images/engr-ma-118.png'):'images/engr-ma-59.png');
var e=document.querySelector('.js18');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/medal-1440.png':'images/medal-960-1.png'):'images/medal-480.png');
var e=document.querySelector('.js19');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/south-177.png':'images/south-118.png'):'images/south-59.png');
var e=document.querySelector('.js20');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/southee-177.png':'images/southee-118.png'):'images/southee-59.png');
var e=document.querySelector('.js21');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/success-177.png':'images/success-118.png'):'images/success-59.png');
var e=document.querySelector('.js22');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/amandabig-1440.jpg':'images/amandabig-960-1.jpg'):'images/amandabig-480.jpg');
var e=document.querySelector('.js23');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/amanda-small-177.png':'images/amanda-small-118.png'):'images/amanda-small-59.png');
var e=document.querySelector('.js24');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/irrfan-177.png':'images/irrfan-118.png'):'images/irrfan-59.png');
var e=document.querySelector('.js25');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/apee-177.png':'images/apee-118.png'):'images/apee-59.png');
var a='data-src';var e=document.querySelector('.js26');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer1-132.png':'images/footer1-88.png'):'images/footer1-44.png');
var a='data-src';var e=document.querySelector('.js27');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer4-135.png':'images/footer4-90-1.png'):'images/footer4-45.png');
var a='data-src';var e=document.querySelector('.js28');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer2-132.png':'images/footer2-88.png'):'images/footer2-44.png');
var a='data-src';var e=document.querySelector('.js29');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer5-132.png':'images/footer5-88.png'):'images/footer5-44.png');
var a='data-src';var e=document.querySelector('.js30');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer3-129.png':'images/footer3-86.png'):'images/footer3-43.png');
var a='data-src';var e=document.querySelector('.js31');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer6-129.png':'images/footer6-86.png'):'images/footer6-43.png');
var a='data-src';var e=document.querySelector('.js32');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-48.png':'images/facebook-32.png'):'images/facebook-16.png');
var a='data-src';var e=document.querySelector('.js33');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-48.png':'images/twitter-32.png'):'images/twitter-16.png');
var a='data-src';var e=document.querySelector('.js34');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-48.png':'images/instagram-32.png'):'images/instagram-16.png');
var a='data-src';var e=document.querySelector('.js35');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-48.png':'images/youtube-32.png'):'images/youtube-16.png');}else{var e=document.querySelector('.js1');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-138.png':'images/logo-92.png'):'images/logo-46.png');
var e=document.querySelector('.js2');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-102.png':'images/playstore-68.png'):'images/playstore-34.png');
var e=document.querySelector('.js3');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-24.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-16.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-8.png');
var e=document.querySelector('.js4');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/search-30.png':'images/search-20.png'):'images/search-10.png');
var a='data-src';var e=document.querySelector('.js5 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/2021-07-960.png':'images/2021-07-640.png'):'images/2021-07-320.png');
var a='data-src';var e=document.querySelector('.js5 .slide1');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/deploy-960.png':'images/deploy-640.png'):'images/deploy-320.png');
var a='data-src';var e=document.querySelector('.js5 .slide2');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/after-960.png':'images/after-640.png'):'images/after-320.png');
var e=document.querySelector('.js6');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/governor-960.png':'images/governor-640.png'):'images/governor-320.png');
var e=document.querySelector('.js7');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/work-117.png':'images/work-78.png'):'images/work-39.png');
var e=document.querySelector('.js8');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/we-re-proud-117.png':'images/we-re-proud-78.png'):'images/we-re-proud-39.png');
var e=document.querySelector('.js9');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/health-117.png':'images/health-78.png'):'images/health-39.png');
var e=document.querySelector('.js10');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/abuja-bank-960.jpg':'images/abuja-bank-640.jpg'):'images/abuja-bank-320.jpg');
var e=document.querySelector('.js11');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/4769-117.png':'images/4769-78.png'):'images/4769-39.png');
var e=document.querySelector('.js12');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/nnpc-117.png':'images/nnpc-78.png'):'images/nnpc-39.png');
var e=document.querySelector('.js13');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/mtn-117.png':'images/mtn-78.png'):'images/mtn-39.png');
var e=document.querySelector('.js14');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/oghene-960.png':'images/oghene-640.png'):'images/oghene-320.png');
var e=document.querySelector('.js15');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/re-innovation-117.png':'images/re-innovation-78.png'):'images/re-innovation-39.png');
var e=document.querySelector('.js16');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/delta-117.png':'images/delta-78.png'):'images/delta-39.png');
var e=document.querySelector('.js17');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/engr-ma-117.png':'images/engr-ma-78.png'):'images/engr-ma-39.png');
var e=document.querySelector('.js18');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/medal-960.png':'images/medal-640.png'):'images/medal-320.png');
var e=document.querySelector('.js19');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/south-117.png':'images/south-78.png'):'images/south-39.png');
var e=document.querySelector('.js20');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/southee-117.png':'images/southee-78.png'):'images/southee-39.png');
var e=document.querySelector('.js21');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/success-117.png':'images/success-78.png'):'images/success-39.png');
var e=document.querySelector('.js22');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/amandabig-960.jpg':'images/amandabig-640.jpg'):'images/amandabig-320.jpg');
var e=document.querySelector('.js23');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/amanda-small-117.png':'images/amanda-small-78.png'):'images/amanda-small-39.png');
var e=document.querySelector('.js24');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/irrfan-117.png':'images/irrfan-78.png'):'images/irrfan-39.png');
var e=document.querySelector('.js25');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/apee-117.png':'images/apee-78.png'):'images/apee-39.png');
var a='data-src';var e=document.querySelector('.js26');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer1-87.png':'images/footer1-58.png'):'images/footer1-29.png');
var a='data-src';var e=document.querySelector('.js27');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer4-90.png':'images/footer4-60.png'):'images/footer4-30.png');
var a='data-src';var e=document.querySelector('.js28');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer2-87.png':'images/footer2-58.png'):'images/footer2-29.png');
var a='data-src';var e=document.querySelector('.js29');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer5-87.png':'images/footer5-58.png'):'images/footer5-29.png');
var a='data-src';var e=document.querySelector('.js30');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer3-87.png':'images/footer3-58.png'):'images/footer3-29.png');
var a='data-src';var e=document.querySelector('.js31');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer6-87.png':'images/footer6-58.png'):'images/footer6-29.png');
var a='data-src';var e=document.querySelector('.js32');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-33.png':'images/facebook-22.png'):'images/facebook-11.png');
var a='data-src';var e=document.querySelector('.js33');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-33.png':'images/twitter-22.png'):'images/twitter-11.png');
var a='data-src';var e=document.querySelector('.js34');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-33.png':'images/instagram-22.png'):'images/instagram-11.png');
var a='data-src';var e=document.querySelector('.js35');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-33.png':'images/youtube-22.png'):'images/youtube-11.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
$('form').h5Validate();$('.js5 .slider').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,overflow: 'hidden',speed: 300,dots: true,arrows: false,infinite: false,autoplay: true,pauseOnHover: true,autoplaySpeed: 2500});$('.js181').mouseenter(function() { $.loadImages('images/footer1-110.png', function() { }) });
$('.js181').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js181-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer1-110.png'; } } });
ldsrc('.js26');ldsrcset('.js182 source');$('.js183').mouseenter(function() { $.loadImages('images/footer4-110.png', function() { }) });
$('.js183').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js183-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer4-110.png'; } } });
ldsrc('.js27');ldsrcset('.js184 source');$('.js185').mouseenter(function() { $.loadImages('images/footer2-110.png', function() { }) });
$('.js185').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js185-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer2-110.png'; } } });
ldsrc('.js28');ldsrcset('.js186 source');$('.js187').mouseenter(function() { $.loadImages('images/footer5-110.png', function() { }) });
$('.js187').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js187-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer5-110.png'; } } });
ldsrc('.js29');ldsrcset('.js188 source');$('.js189').mouseenter(function() { $.loadImages('images/footer3-110.png', function() { }) });
$('.js189').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js189-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer3-110.png'; } } });
ldsrc('.js30');ldsrcset('.js190 source');$('.js191').mouseenter(function() { $.loadImages('images/footer6-110.png', function() { }) });
$('.js191').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js191-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer6-110.png'; } } });
ldsrc('.js31');ldsrcset('.js192 source');ldsrc('.js32');ldsrcset('.js193 source');ldsrc('.js33');ldsrcset('.js194 source');ldsrc('.js34');ldsrcset('.js195 source');ldsrc('.js35');ldsrcset('.js196 source');
});