(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

var lwi=-1;function thresholdPassed(){var w=$(window).width();var p=false;var cw=0;if(w>=480){cw++;}if(w>=768){cw++;}if(w>=960){cw++;}if(w>=1200){cw++;}if(lwi!=cw){p=true;}lwi=cw;return p;}
ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t),r=e.getAttribute("data-src");e.setAttribute("src",r)};!function(){if("Promise"in window){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),s=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),i=location.href.replace(/#[^#]+$/,"");o.add(i);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(s){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var i=new XMLHttpRequest;i.open("GET",t,i.withCredentials=!0),i.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},l={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},l),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},l)}}();

$(function(){
r=function(){if(thresholdPassed()){dpi=window.devicePixelRatio;if($(window).width()>=1200){var e=document.querySelector('.js217');e.setAttribute('src',(dpi>1)?'images/logo-404.png':'images/logo-202.png');
var e=document.querySelector('.js218');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-393.png':'images/playstore-262.png'):'images/playstore-131.png');
var e=document.querySelector('.js219');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-93.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-62.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-31.png');
var e=document.querySelector('.js220');e.setAttribute('src','images/search-40.png');
var a='data-src';var e=document.querySelector('.js221 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/we-ll-deploy-1200.png');
var e=document.querySelector('.js222');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/save_post-66.png':'images/save_post-44.png'):'images/save_post-22.png');
var e=document.querySelector('.js223');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/share_post-72.png':'images/share_post-48.png'):'images/share_post-24.png');
var e=document.querySelector('.js224');e.setAttribute('src','images/20210805104100-1200.jpg');
var e=document.querySelector('.js225');e.setAttribute('src','images/omoagege-1200.jpg');
var a='data-src';var e=document.querySelector('.js226');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/profile_pic-216.png':'images/profile_pic-144.png'):'images/profile_pic-72.png');
var a='data-src';var e=document.querySelector('.js228');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer1-110-1.png');
var a='data-src';var e=document.querySelector('.js229');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer4-110-1.png');
var a='data-src';var e=document.querySelector('.js230');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer2-110-1.png');
var a='data-src';var e=document.querySelector('.js231');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer5-110-1.png');
var a='data-src';var e=document.querySelector('.js232');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer3-110-1.png');
var a='data-src';var e=document.querySelector('.js233');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer6-110-1.png');
var a='data-src';var e=document.querySelector('.js234');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-120.png':'images/facebook-80.png'):'images/facebook-40.png');
var a='data-src';var e=document.querySelector('.js235');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-120.png':'images/twitter-80.png'):'images/twitter-40.png');
var a='data-src';var e=document.querySelector('.js236');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-120.png':'images/instagram-80.png'):'images/instagram-40.png');
var a='data-src';var e=document.querySelector('.js237');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-120.png':'images/youtube-80.png'):'images/youtube-40.png');}else if($(window).width()>=960){var e=document.querySelector('.js217');e.setAttribute('src',(dpi>1)?'images/logo-274.png':'images/logo-137.png');
var e=document.querySelector('.js218');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-312.png':'images/playstore-208.png'):'images/playstore-104.png');
var e=document.querySelector('.js219');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-75.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-50.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-25.png');
var e=document.querySelector('.js220');e.setAttribute('src','images/search-32-1.png');
var a='data-src';var e=document.querySelector('.js221 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/we-ll-deploy-960-2.png');
var e=document.querySelector('.js222');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/save_post-51.png':'images/save_post-34.png'):'images/save_post-17.png');
var e=document.querySelector('.js223');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/share_post-57.png':'images/share_post-38.png'):'images/share_post-19.png');
var e=document.querySelector('.js224');e.setAttribute('src','images/20210805104100-960-1.jpg');
var e=document.querySelector('.js225');e.setAttribute('src','images/omoagege-960.jpg');
var a='data-src';var e=document.querySelector('.js226');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/profile_pic-171.png':'images/profile_pic-114.png'):'images/profile_pic-57-1.png');
var a='data-src';var e=document.querySelector('.js228');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer1-88-1.png');
var a='data-src';var e=document.querySelector('.js229');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer4-88.png');
var a='data-src';var e=document.querySelector('.js230');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer2-88-1.png');
var a='data-src';var e=document.querySelector('.js231');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer5-88-1.png');
var a='data-src';var e=document.querySelector('.js232');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer3-88.png');
var a='data-src';var e=document.querySelector('.js233');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,'images/footer6-88.png');
var a='data-src';var e=document.querySelector('.js234');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-96.png':'images/facebook-64.png'):'images/facebook-32-1.png');
var a='data-src';var e=document.querySelector('.js235');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-96.png':'images/twitter-64.png'):'images/twitter-32-1.png');
var a='data-src';var e=document.querySelector('.js236');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-96.png':'images/instagram-64.png'):'images/instagram-32-1.png');
var a='data-src';var e=document.querySelector('.js237');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-96.png':'images/youtube-64.png'):'images/youtube-32-1.png');}else if($(window).width()>=768){var e=document.querySelector('.js217');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-330.png':'images/logo-220.png'):'images/logo-110.png');
var e=document.querySelector('.js218');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-252.png':'images/playstore-168.png'):'images/playstore-84.png');
var e=document.querySelector('.js219');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-60.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-40.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-20.png');
var e=document.querySelector('.js220');e.setAttribute('src',(dpi>1)?'images/search-52.png':'images/search-26.png');
var a='data-src';var e=document.querySelector('.js221 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/we-ll-deploy-1536.png':'images/we-ll-deploy-768.png');
var e=document.querySelector('.js222');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/save_post-42.png':'images/save_post-28.png'):'images/save_post-14.png');
var e=document.querySelector('.js223');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/share_post-45.png':'images/share_post-30.png'):'images/share_post-15.png');
var e=document.querySelector('.js224');e.setAttribute('src',(dpi>1)?'images/20210805104100-1534.jpg':'images/20210805104100-767.jpg');
var e=document.querySelector('.js225');e.setAttribute('src',(dpi>1)?'images/omoagege-1534.jpg':'images/omoagege-767.jpg');
var a='data-src';var e=document.querySelector('.js226');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/profile_pic-138.png':'images/profile_pic-92.png'):'images/profile_pic-46.png');
var a='data-src';var e=document.querySelector('.js228');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer1-140.png':'images/footer1-70.png');
var a='data-src';var e=document.querySelector('.js229');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer4-140.png':'images/footer4-70.png');
var a='data-src';var e=document.querySelector('.js230');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer2-140.png':'images/footer2-70.png');
var a='data-src';var e=document.querySelector('.js231');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer5-140.png':'images/footer5-70.png');
var a='data-src';var e=document.querySelector('.js232');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer3-140.png':'images/footer3-70.png');
var a='data-src';var e=document.querySelector('.js233');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/footer6-140.png':'images/footer6-70.png');
var a='data-src';var e=document.querySelector('.js234');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-75.png':'images/facebook-50.png'):'images/facebook-25.png');
var a='data-src';var e=document.querySelector('.js235');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-75.png':'images/twitter-50.png'):'images/twitter-25.png');
var a='data-src';var e=document.querySelector('.js236');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-78.png':'images/instagram-52.png'):'images/instagram-26.png');
var a='data-src';var e=document.querySelector('.js237');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-78.png':'images/youtube-52.png'):'images/youtube-26.png');}else if($(window).width()>=480){var e=document.querySelector('.js217');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-207.png':'images/logo-138-1.png'):'images/logo-69.png');
var e=document.querySelector('.js218');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-150.png':'images/playstore-100.png'):'images/playstore-50.png');
var e=document.querySelector('.js219');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-39.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-26.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-13.png');
var e=document.querySelector('.js220');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/search-48.png':'images/search-32.png'):'images/search-16.png');
var a='data-src';var e=document.querySelector('.js221 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/we-ll-deploy-1440.png':'images/we-ll-deploy-960-1.png'):'images/we-ll-deploy-480.png');
var e=document.querySelector('.js222');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/save_post-27.png':'images/save_post-18-1.png'):'images/save_post-9.png');
var e=document.querySelector('.js223');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/share_post-27.png':'images/share_post-18-1.png'):'images/share_post-9.png');
var e=document.querySelector('.js224');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/20210805104100-1437.jpg':'images/20210805104100-958.jpg'):'images/20210805104100-479.jpg');
var e=document.querySelector('.js225');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/omoagege-1437.jpg':'images/omoagege-958.jpg'):'images/omoagege-479.jpg');
var a='data-src';var e=document.querySelector('.js226');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/profile_pic-87.png':'images/profile_pic-58.png'):'images/profile_pic-29.png');
var a='data-src';var e=document.querySelector('.js228');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer1-132.png':'images/footer1-88.png'):'images/footer1-44.png');
var a='data-src';var e=document.querySelector('.js229');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer4-135.png':'images/footer4-90-1.png'):'images/footer4-45.png');
var a='data-src';var e=document.querySelector('.js230');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer2-132.png':'images/footer2-88.png'):'images/footer2-44.png');
var a='data-src';var e=document.querySelector('.js231');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer5-132.png':'images/footer5-88.png'):'images/footer5-44.png');
var a='data-src';var e=document.querySelector('.js232');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer3-129.png':'images/footer3-86.png'):'images/footer3-43.png');
var a='data-src';var e=document.querySelector('.js233');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer6-129.png':'images/footer6-86.png'):'images/footer6-43.png');
var a='data-src';var e=document.querySelector('.js234');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-48.png':'images/facebook-32.png'):'images/facebook-16.png');
var a='data-src';var e=document.querySelector('.js235');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-48.png':'images/twitter-32.png'):'images/twitter-16.png');
var a='data-src';var e=document.querySelector('.js236');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-48.png':'images/instagram-32.png'):'images/instagram-16.png');
var a='data-src';var e=document.querySelector('.js237');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-48.png':'images/youtube-32.png'):'images/youtube-16.png');}else{var e=document.querySelector('.js217');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/logo-138.png':'images/logo-92.png'):'images/logo-46.png');
var e=document.querySelector('.js218');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/playstore-102.png':'images/playstore-68.png'):'images/playstore-34.png');
var e=document.querySelector('.js219');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-24.png':'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-16.png'):'images/calendar-date-computer-icons-clip-art-calendar-350b8fd1f6d77a8a3d46f3b5ea8bd40f-8.png');
var e=document.querySelector('.js220');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/search-30.png':'images/search-20.png'):'images/search-10.png');
var a='data-src';var e=document.querySelector('.js221 .slide0');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/we-ll-deploy-960.png':'images/we-ll-deploy-640.png'):'images/we-ll-deploy-320.png');
var e=document.querySelector('.js222');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/save_post-18.png':'images/save_post-12.png'):'images/save_post-6.png');
var e=document.querySelector('.js223');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/share_post-18.png':'images/share_post-12.png'):'images/share_post-6.png');
var e=document.querySelector('.js224');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/20210805104100-960.jpg':'images/20210805104100-640.jpg'):'images/20210805104100-320.jpg');
var e=document.querySelector('.js225');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/omoagege-957.jpg':'images/omoagege-638.jpg'):'images/omoagege-319.jpg');
var a='data-src';var e=document.querySelector('.js226');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/profile_pic-57.png':'images/profile_pic-38.png'):'images/profile_pic-19.png');
var a='data-src';var e=document.querySelector('.js228');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer1-87.png':'images/footer1-58.png'):'images/footer1-29.png');
var a='data-src';var e=document.querySelector('.js229');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer4-90.png':'images/footer4-60.png'):'images/footer4-30.png');
var a='data-src';var e=document.querySelector('.js230');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer2-87.png':'images/footer2-58.png'):'images/footer2-29.png');
var a='data-src';var e=document.querySelector('.js231');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer5-87.png':'images/footer5-58.png'):'images/footer5-29.png');
var a='data-src';var e=document.querySelector('.js232');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer3-87.png':'images/footer3-58.png'):'images/footer3-29.png');
var a='data-src';var e=document.querySelector('.js233');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/footer6-87.png':'images/footer6-58.png'):'images/footer6-29.png');
var a='data-src';var e=document.querySelector('.js234');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/facebook-33.png':'images/facebook-22.png'):'images/facebook-11.png');
var a='data-src';var e=document.querySelector('.js235');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/twitter-33.png':'images/twitter-22.png'):'images/twitter-11.png');
var a='data-src';var e=document.querySelector('.js236');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/instagram-33.png':'images/instagram-22.png'):'images/instagram-11.png');
var a='data-src';var e=document.querySelector('.js237');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/youtube-33.png':'images/youtube-22.png'):'images/youtube-11.png');}}};
if(!window.HTMLPictureElement){$(window).resize(r);r();}
(function(){$('a[href^="#"]:not(.allowConsent,.noConsent,.denyConsent,.removeConsent)').each(function(i,e){$(e).click(function(){var t=e.hash.length>1?$('[name="'+e.hash.slice(1)+'"]').offset().top:0;return $("html, body").animate({scrollTop:t},400),!1})})})();
$('form').h5Validate();$('.js221 .slider').slick({lazyLoad: 'ondemand',slidesToShow: 1,slidesToScroll: 1,overflow: 'hidden',speed: 300,dots: true,arrows: false,infinite: false,autoplay: true,pauseOnHover: true,autoplaySpeed: 2500});ldsrc('.js226');ldsrcset('.js327 source');$('.js328').mouseenter(function() { $.loadImages('images/footer1-110.png', function() { }) });
$('.js328').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js328-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer1-110.png'; } } });
ldsrc('.js228');ldsrcset('.js329 source');$('.js330').mouseenter(function() { $.loadImages('images/footer4-110.png', function() { }) });
$('.js330').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js330-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer4-110.png'; } } });
ldsrc('.js229');ldsrcset('.js331 source');$('.js332').mouseenter(function() { $.loadImages('images/footer2-110.png', function() { }) });
$('.js332').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js332-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer2-110.png'; } } });
ldsrc('.js230');ldsrcset('.js333 source');$('.js334').mouseenter(function() { $.loadImages('images/footer5-110.png', function() { }) });
$('.js334').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js334-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer5-110.png'; } } });
ldsrc('.js231');ldsrcset('.js335 source');$('.js336').mouseenter(function() { $.loadImages('images/footer3-110.png', function() { }) });
$('.js336').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js336-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer3-110.png'; } } });
ldsrc('.js232');ldsrcset('.js337 source');$('.js338').mouseenter(function() { $.loadImages('images/footer6-110.png', function() { }) });
$('.js338').magnificPopup({ type: 'image', closeOnContentClick: true, closeBtnInside: false, mainClass: 'mfp-fade js338-lightbox mfp-no-margins mfp-with-zoom', image: { verticalFit: true }, zoom: { enabled: true, duration: 300 }, callbacks: { elementParse: function(item) { item.src = 'images/footer6-110.png'; } } });
ldsrc('.js233');ldsrcset('.js339 source');ldsrc('.js234');ldsrcset('.js340 source');ldsrc('.js235');ldsrcset('.js341 source');ldsrc('.js236');ldsrcset('.js342 source');ldsrc('.js237');ldsrcset('.js343 source');
});